---
title: Правило анализа кода CA2153 для исключений поврежденного состояния (анализ кода)
description: Сведения о правиле анализа кода CA2153 для исключений поврежденного состояния
ms.date: 02/19/2019
ms.topic: reference
author: gewarren
ms.author: gewarren
ms.openlocfilehash: 32d9c6ef19d0cf1fa869f21cff7dc90d95c44277
ms.sourcegitcommit: 05d0087dfca85aac9ca2960f86c5efd218bf833f
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 03/30/2021
ms.locfileid: "99714876"
---
# <a name="ca2153-avoid-handling-corrupted-state-exceptions"></a>CA2153. Не обрабатывайте исключения поврежденного состояния

| | Значение |
|-|-|
| **Идентификатор правила** |CA2153|
| **Категория** |[Безопасность](security-warnings.md)|
| **Исправление является критическим или не критическим** |Не критическое|

## <a name="cause"></a>Причина

[Исключения поврежденного состояния (CSE)](/archive/msdn-magazine/2009/february/clr-inside-out-handling-corrupted-state-exceptions) указывают на то, что в процессе имеется повреждение памяти. Если перехватывать их вместо того, чтобы позволить процессу завершиться сбоем, это может привести к уязвимостям в системе безопасности, если злоумышленнику удастся поместить эксплойт в поврежденную область памяти.

## <a name="rule-description"></a>Описание правила

Исключение CSE указывает на то, что состояние процесса было повреждено, и не перехватывается системой. В случае повреждения состояния общий обработчик перехватывает это исключение, только если вы пометили метод атрибутом <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute?displayProperty=fullName>. По умолчанию [среда CLR](../../../standard/clr.md) не вызывает обработчики catch для исключений CSE.

Наиболее надежный вариант — разрешить аварийное завершение процесса без перехвата исключений такого типа. Даже код ведения журналов может позволить злоумышленникам использовать ошибки повреждения памяти.

Это предупреждение срабатывает при перехвате исключений CSE с помощью общего обработчика, который перехватывает все исключения, например `catch (System.Exception e)` или `catch`, без параметра исключения.

## <a name="how-to-fix-violations"></a>Устранение нарушений

Чтобы устранить эту проблему, выполните любое из следующих действий.

- Удалите атрибут <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute>. При этом восстанавливается поведение среды выполнения по умолчанию, при котором исключения CSE не передаются в обработчики catch.

- Удалите общий обработчик catch и используйте обработчики, перехватывающие исключения определенных типов. Это могут быть и исключения CSE при условии, что они могут быть обработаны безопасным образом (что бывает редко).

- Повторно создайте исключение CSE в обработчике catch, чтобы передать его вызывающему объекту и вызвать завершение выполняющегося процесса.

## <a name="when-to-suppress-warnings"></a>Условия для отключения предупреждений

Для этого правила отключать вывод предупреждений не следует.

## <a name="pseudo-code-example"></a>Пример псевдокода

### <a name="violation"></a>Нарушение

В приведенном ниже псевдокоде показан шаблон, обнаруживаемый этим правилом.

```csharp
[HandleProcessCorruptedStateExceptions]
// Method that handles CSE exceptions.
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-1---remove-the-attribute"></a>Решение 1. Удаление атрибута

При удалении атрибута <xref:System.Runtime.ExceptionServices.HandleProcessCorruptedStateExceptionsAttribute> исключения поврежденного состояния не будут обрабатываться методом.

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Handle exception.
    }
}
```

### <a name="solution-2---catch-specific-exceptions"></a>Решение 2. Перехват определенных исключений

Удалите общий обработчик catch и перехватывайте только исключения определенных типов.

```csharp
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (IOException e)
    {
        // Handle IOException.
    }
    catch (UnauthorizedAccessException e)
    {
        // Handle UnauthorizedAccessException.
    }
}
```

### <a name="solution-3---rethrow"></a>Решение 3. Повторное создание

Повторно создайте исключение.

```csharp
[HandleProcessCorruptedStateExceptions]
void TestMethod1()
{
    try
    {
        FileStream fileStream = new FileStream("name", FileMode.Create);
    }
    catch (Exception e)
    {
        // Rethrow the exception.
        throw;
    }
}
```
