---
title: Руководство по программированию на C#. Исключения и обработка исключений
description: Узнайте об исключениях и обработке исключений. Эти функции в C# помогают справиться с непредвиденными или исключительными проблемами, которые возникают при выполнении программы.
ms.date: 12/09/2020
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 245299707254c7bafb4589ee8031a107921ca2a7
ms.sourcegitcommit: e7e0921d0a10f85e9cb12f8b87cc1639a6c8d3fe
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 04/09/2021
ms.locfileid: "107255406"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="b5ba2-104">Исключения и обработка исключений (Руководство по программированию в C#)</span><span class="sxs-lookup"><span data-stu-id="b5ba2-104">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="b5ba2-105">Функции обработки исключений в языке C# помогают вам справиться с непредвиденными или исключительными проблемами, которые возникают при выполнении программы.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-105">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="b5ba2-106">При обработке исключений используются ключевые слова `try`, `catch` и `finally` для действий, которые могут оказаться неудачными. Это позволяет обрабатывать ошибки так, как кажется разумным, а также правильно высвобождать ресурсы.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-106">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it's reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="b5ba2-107">Исключения могут создаваться средой выполнения (CLR), платформой .NET , библиотеками сторонних поставщиков или кодом самого приложения.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-107">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="b5ba2-108">Чтобы создать исключение, используйте ключевое слово `throw`.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-108">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="b5ba2-109">Во многих случаях исключение может создаваться не тем методом, который вызывается в вашем коде, а одним из последующих методов в стеке вызовов.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-109">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="b5ba2-110">Если создается такое исключение, среда CLR разворачивает стек, находит метод с блоком `catch` для исключений соответствующего типа и выполняет первый такой обнаруженный блок `catch`.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-110">When an exception is thrown, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="b5ba2-111">Если подходящий блок `catch` не будет обнаружен во всем стеке вызовов, среда CLR завершает процесс и выводит сообщение для пользователя.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-111">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="b5ba2-112">В этом примере метод выполняет проверку деления на нуль и перехватывает ошибку.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-112">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="b5ba2-113">Если не использовать обработку исключений, такая программа завершит работу с ошибкой **DivideByZeroException was unhandled** (Исключение DivideByZero не обработано).</span><span class="sxs-lookup"><span data-stu-id="b5ba2-113">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

:::code language="csharp" source="snippets/exceptions/ExceptionTest.cs" ID="ExceptionTest":::

## <a name="exceptions-overview"></a><span data-ttu-id="b5ba2-114">Общие сведения об исключениях</span><span class="sxs-lookup"><span data-stu-id="b5ba2-114">Exceptions Overview</span></span>

<span data-ttu-id="b5ba2-115">Исключения имеют следующие свойства.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-115">Exceptions have the following properties:</span></span>

- <span data-ttu-id="b5ba2-116">Исключения представляют собой типы, производные в конечном счете от `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-116">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="b5ba2-117">Используйте блок `try` для выполнения таких инструкций, которые могут создавать исключения.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-117">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="b5ba2-118">Когда внутри такого блока `try` возникает исключение, поток управления переходит к первому подходящему обработчику исключений в стеке вызовов.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-118">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="b5ba2-119">В C# ключевое слово `catch` обозначает обработчик исключений.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-119">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="b5ba2-120">Если для созданного исключения не существует обработчиков, выполнение программы прекращается с сообщением об ошибке.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-120">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="b5ba2-121">Не перехватывайте исключение, если вы не намерены его обрабатывать с сохранением известного состояния приложения.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-121">Don't catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="b5ba2-122">Если вы перехватываете `System.Exception`, создайте его заново в конце блока `catch`, используя ключевое слово `throw`.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-122">If you catch `System.Exception`, rethrow it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="b5ba2-123">Если блок `catch` определяет переменную исключения, ее можно использовать для получения дополнительных сведений о типе созданного исключения.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-123">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="b5ba2-124">Программа может явным образом создавать исключения с помощью ключевого слова `throw`.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-124">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="b5ba2-125">Объекты исключения содержат подробные сведения об ошибке, например состояние стека вызовов и текстовое описание ошибки.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-125">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="b5ba2-126">Код в блоке `finally` выполняется даже в том случае, если создано исключение.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-126">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="b5ba2-127">Используйте блок `finally`, чтобы высвободить ресурсы, например закрыть потоки и файлы, которые были открыты внутри блока `try`.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-127">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="b5ba2-128">Управляемые исключения реализованы в платформе .NET на основе структурированного механизма обработки исключений Win32.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-128">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="b5ba2-129">Дополнительные сведения см. в статьях [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) (Структурированная обработка исключений в C и C++) и [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm) (Интенсивное погружение в структурированную обработку исключений на платформе Win32).</span><span class="sxs-lookup"><span data-stu-id="b5ba2-129">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="c-language-specification"></a><span data-ttu-id="b5ba2-130">Спецификация языка C#</span><span class="sxs-lookup"><span data-stu-id="b5ba2-130">C# Language Specification</span></span>

<span data-ttu-id="b5ba2-131">Дополнительные сведения см. в разделе [Исключения](~/_csharplang/spec/exceptions.md) в [Спецификации языка C#](/dotnet/csharp/language-reference/language-specification/introduction).</span><span class="sxs-lookup"><span data-stu-id="b5ba2-131">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="b5ba2-132">Спецификация языка является предписывающим источником информации о синтаксисе и использовании языка C#.</span><span class="sxs-lookup"><span data-stu-id="b5ba2-132">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="b5ba2-133">См. также</span><span class="sxs-lookup"><span data-stu-id="b5ba2-133">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="b5ba2-134">Ключевые слова в C#</span><span class="sxs-lookup"><span data-stu-id="b5ba2-134">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="b5ba2-135">throw</span><span class="sxs-lookup"><span data-stu-id="b5ba2-135">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="b5ba2-136">try-catch</span><span class="sxs-lookup"><span data-stu-id="b5ba2-136">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="b5ba2-137">try-finally</span><span class="sxs-lookup"><span data-stu-id="b5ba2-137">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="b5ba2-138">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="b5ba2-138">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="b5ba2-139">Исключения</span><span class="sxs-lookup"><span data-stu-id="b5ba2-139">Exceptions</span></span>](../../../standard/exceptions/index.md)
